** Links
http://habrahabr.ru/post/191994/
http://irrlicht.ru/
http://irrlicht.sourceforge.net/forum/viewtopic.php?t=43979


** Установка
1. svn checkout svn://svn.code.sf.net/p/irrlicht/code/trunk irrlicht
2. On the Irrlicht folder type: cd source/Irrlicht && make
3. Install the library and headers from the directory irrlicht-1.#
  1. Type: cd ../..
  2. Type: sudo cp -r include/* /usr/local/include/
  3. Type: sudo cp lib/Linux/libIrrlicht.a /usr/local/lib
4. Compile the examples.
  1. Type: cd examples
  2. Type: chmod +x buildAllExamples.sh
  3. Type: ./buildAllExamples.sh
  4. Type: cd ../bin/Linux

** Особенности
1. librsvg распространяется под лицензией GPL и LGPL, при использовании можно выбрать лицензию которой руководствоваться. 
GPL - предполагает, что если в проекте используется GPL код, то весь остальной код тоже должен распространяться под GPL,
LGPL - при статической линковке требует, чтобы код был открыт, если линковка динамическая (т.е. длл-ка может быть подменена на др версию),
то код может быть под любой лицензией.

** Реализация
1. За образец был взят аналогичный модуль для загрузки .png изображений CImageLoaderPNG.
Модули загрузки изображений унифицированны в Irrlicht и должны реализовывать интерфейс IImageLoader.
2. 
	 IVideoDriver
		virtual ITexture* getTexture(const io::path& filename) = 0;
		virtual ITexture* getTexture(io::IReadFile* file) =0;

	 

** Дейлик

